### ISSUE TITLE
Proposal: API support context.Context

### ISSUE THREAD

**Issue by ipfans** [Fs02/rel#28]
The purpose of carrying the context around would be to have it available in callback functions or execution timeout, where it could be used to enhance logging, trace execution times (with opentracing etc), or perhaps carry some authentication context or user id to the callbacks.

**Comment by Fs02** [comment]
Hi, right now I'm still considering whether to add context to the APIs or not. It's because there's argument against it: https://faiface.github.io/post/context-should-go-away-go2/

But I don't think there's anything to loose by adding context to the API, and like your say, the context can be usefull to adds more information to the logging. Thanks :)
